backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "tiere"
    label: "Meerschweinchen"
    folder: "src/data/tiere"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Geburtsdatum", name: "geburt", widget: "date" }
      - { label: "Geschlecht", name: "geschlecht", widget: "select", options: ["Weiblich", "Männlich"] }
      - { label: "Farbe", name: "farbe", widget: "string" }
      - { label: "Beschreibung", name: "beschreibung", widget: "text" }
      - { label: "Bild", name: "bild", widget: "image" }
